# Capacitação Vialab  # Atividade 1

## Exercícios de análise exploratória
### Data de atualização: 04/02/2022

# Objetivo: Desenvolver habilidades de manipulação e análise de dados

#Tarefa 1:

°Explorar os datasets wine_quality_red e wine_quality_white
 
°Concatenar os dataframes em um único dataframe
 
°Apresentar os últimos 7 dados do dataframe único
 
°Apresentar informações sobre todas as colunas (como a contagem de não nulos)
 
°Fazer a soma de todos os dados nulos por coluna
 
°Apresentar a contagem, média, desvio padrão e os quartis de todas as colunas
 
°Apresentar a quantidade de vinhos para cada "quality" Ex: Existem 30
vinhos com quality = 3
 
°Apresentar um heatmap da correlação entre todas as colunas
 
°Criar um boxplot para identificar outliers


Dica 1: Para entender quartis e boxplots recomendamos as aulas 19 e 20: https://didatica.tech/curso-de-python-para-machine-learning-e-ciencia-de-dados-gratuito/

Dica 2: Há funções prontas para tudo na biblioteca Pandas

###Tarefa extra:

Logo após concatenar, Acrescentar uma nova coluna "rate" ao dataframe único, onde vinhos com 

qualidade < 5 == 'Péssimo', 

qualidade < 7 == 'Médio', 

else = 'Bom'

Definir o tipo da nova coluna como "category"

###Código

In [ ]:
#Importação dos pacotes necessários 
import pandas as pd #Permite manipularmos DataFrames com facilidade
import matplotlib.pyplot as plt #Biblioteca para plot de gráficos
import seaborn as sns #Realiza a estilização dos gráficos
import numpy as np #Permite a realização de cálculos com matrizes e arrays

In [ ]:
#Importação do dataset Wine quality red 
Wine_quality_red = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', sep=';')
Wine_quality_red.head(10)

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5
5            7.4              0.66         0.00  ...       0.56      9.4        5
6            7.9              0.60         0.06  ...       0.46      9.4        5
7            7.3              0.65         0.00  ...       0.47     10.0        7
8            7.8              0.58         0.02  ...       0.57      9.5        7
9            7.5              0.50         0.36  ...       0.80     10.5        5

[10 rows x 12 columns]

In [ ]:
#Importação do dataset Wine quality white
Wine_quality_white = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv', sep=';')
Wine_quality_white.head(10)

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.0              0.27         0.36  ...       0.45      8.8        6
1            6.3              0.30         0.34  ...       0.49      9.5        6
2            8.1              0.28         0.40  ...       0.44     10.1        6
3            7.2              0.23         0.32  ...       0.40      9.9        6
4            7.2              0.23         0.32  ...       0.40      9.9        6
5            8.1              0.28         0.40  ...       0.44     10.1        6
6            6.2              0.32         0.16  ...       0.47      9.6        6
7            7.0              0.27         0.36  ...       0.45      8.8        6
8            6.3              0.30         0.34  ...       0.49      9.5        6
9            8.1              0.22         0.43  ...       0.45     11.0        6

[10 rows x 12 columns]

#Tarefa 2

Agora que você aprendeu um pouco mais sobre o uso de Pandas, vamos treinar um pouco com a geração de gráficos no Matplotlib e Seaborn.

Essas ferramentas podem ser combinadas para criar diversas visualizações que nos ajudam a entender as relações e sentido de nossos dados, transformando-os em conhecimento.

Utilizando essas bibliotecas, crie gráficos que possam analisar a distribuição dos dados, suas relações e crie vizualizações que tragam um maior sentido para o conjunto analisado, da forma que achar mais interessante.

Dica 1: Comandos do Seaborn e Matplot podem ser usados em conjunto

Dica 2: No git, há uma mini-apostila com materiais sobre gráficos e seus usos